image:
  tag: "3.0.3"

executor: KubernetesExecutor

dags:
  persistence:
    enabled: true
    existingClaim: dags-pvc

logs:
  persistence:
    enabled: true
    existingClaim: logs-pvc

webserver:
  service:
    type: NodePort
    ports:
      - name: airflow-ui
        port: 8080
        targetPort: 8080
        nodePort: 32080

postgresql:
  enabled: true

config:
  core:
    load_examples: "False"
